package GUI;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.Font;
import java.awt.Point;
import javax.swing.ImageIcon;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JLabel;

public class DetailGUI extends JFrame{
    private JLabel lbl,id1,id2,namelbl1,namelbl2,pricelbl1,pricelbl2,tonkho1,tonkho2,km1,km2;
    int x,y;
    private Font f = new Font("Arial",Font.BOLD,12);
    private Font f2 = new Font("Arial",Font.PLAIN,12);
    BanhangGUI home;
    public DetailGUI(String id,String name,int price,int tonkho,int km,Point p){
        setSize(300,200);
        setResizable(false);
        setUndecorated(true);
        setLocation(new Point(p));
        setBackground(Color.WHITE);
        setLayout(new FlowLayout(0,0,2));
        lbl = new JLabel("Thông tin chi tiết");
        lbl.setForeground(Color.red);
        lbl.setIcon(new ImageIcon(this.getClass().getResource("/Icons/star.png")));
        lbl.setFont(f);
        lbl.setPreferredSize(new Dimension(250,30));
        id1 = new JLabel("Mã sản phẩm:");
        id1.setHorizontalAlignment(JLabel.LEFT);
        id1.setForeground(Color.red);
        id1.setIcon(new ImageIcon(this.getClass().getResource("/Icons/star.png")));
        id1.setFont(f);
        id1.setPreferredSize(new Dimension(150,30));
        id2 = new JLabel(id);
        id2.setHorizontalAlignment(JLabel.RIGHT);
        id2.setFont(f);
        id2.setPreferredSize(new Dimension(150,30));
        namelbl1 = new JLabel("Tên sản phẩm");
        id1.setHorizontalAlignment(JLabel.LEFT);
        namelbl1.setForeground(Color.red);
        namelbl1.setIcon(new ImageIcon(this.getClass().getResource("/Icons/star.png")));
        namelbl1.setFont(f);
        namelbl2 = new JLabel(name);
        id1.setHorizontalAlignment(JLabel.RIGHT);
        namelbl2.setFont(f);
        namelbl2.setPreferredSize(new Dimension(150,30));
        pricelbl1 = new JLabel("Đơn giá");
        id1.setHorizontalAlignment(JLabel.LEFT);
        pricelbl1.setForeground(Color.red);
        pricelbl1.setIcon(new ImageIcon(this.getClass().getResource("/Icons/star.png")));
        pricelbl1.setFont(f);
        pricelbl1.setPreferredSize(new Dimension(150,30));
        pricelbl2 = new JLabel(Integer.toString(price));
        id1.setHorizontalAlignment(JLabel.RIGHT);
        pricelbl2.setFont(f);
        pricelbl2.setPreferredSize(new Dimension(150,30));
        tonkho1 = new JLabel("Tồn kho");
        id1.setHorizontalAlignment(JLabel.LEFT);
        tonkho1.setForeground(Color.red);
        tonkho1.setIcon(new ImageIcon(this.getClass().getResource("/Icons/star.png")));
        tonkho1.setFont(f);
        tonkho1.setPreferredSize(new Dimension(150,30));
        tonkho2 = new JLabel(Integer.toString(tonkho));
        id1.setHorizontalAlignment(JLabel.RIGHT);
        tonkho2.setFont(f);
        tonkho2.setPreferredSize(new Dimension(150,30));
        km1 = new JLabel("Khuyến mãi");
        id1.setHorizontalAlignment(JLabel.LEFT);
        km1.setForeground(Color.red);
        km1.setIcon(new ImageIcon(this.getClass().getResource("/Icons/star.png")));
        km1.setFont(f);
        km1.setPreferredSize(new Dimension(150,30));
        String s = (km == 1) ? "Có" : "Không";
        km2 = new JLabel(s);
          id1.setHorizontalAlignment(JLabel.RIGHT);
        km2.setFont(f2);
        km2.setPreferredSize(new Dimension(150,30));
        add(lbl);
        add(id1);
        add(id2);
        add(namelbl1);
        add(namelbl2);
        add(pricelbl1);
        add(pricelbl2);
        add(tonkho1);
        add(tonkho2);
        add(km1);
        add(km2);
    }
}
